const PALETTE = {
  BLACK: '#092328',
  TEAL: '#12544F',
  GREEN: '#2A835F',
  SAGE: '#8BBB92',

  WHITE: '#FFFFFF',
  RED: '#C94A4A',
  YELLOW: '#C58A32',
  BLUE: '#477D9A',
  TRANSPARENT_BLACK: 'rgba(9, 35, 40, 0.5)',
  TRANSPARENT: 'transparent',
} as const;

export const COLORS = {
  PRIMARY: PALETTE.TEAL,
  TEXT_PRIMARY: PALETTE.BLACK,
  TEXT_SECONDARY: PALETTE.GREEN,
  BORDER: PALETTE.SAGE,
  BACKGROUND: PALETTE.WHITE,
  OVERLAY: PALETTE.TRANSPARENT_BLACK,
} as const;
